// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://freiywrvibezwycsjygl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyZWl5d3J2aWJlend5Y3NqeWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTMzNDYsImV4cCI6MjA2OTg4OTM0Nn0.Ecl6ZCkJee8VCbGQ7BBxxBtk3ixfkCdaBgXD4xLarJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});